apiVersion: v1
kind: Service
metadata:
  name: nodejs-backend-service
spec:
  selector:
    app: kubeecommerce
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8090
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedeploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kubeecommerce
  template:
    metadata:
      labels:
        app: kubeecommerce
    spec:
      containers:
      - name: kubecontainer
        image: koriditmeyer/ecommercebackend_mvc:1.3
        ports:
        - containerPort: 8090
        env:
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: PORT
        - name: NODE_ENV
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: NODE_ENV
        - name: PERSISTENCE
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: PERSISTENCE
        - name: CNX_STR
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: CNX_STR
        - name: ROUNDS
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: ROUNDS
        - name: JWT_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: JWT_PRIVATE_KEY
        - name: JWT_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: JWT_COOKIE_SECRET
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: SESSION_SECRET
        - name: GITHUBAPPID
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: GITHUBAPPID
        - name: GITHUBCLIENTEID
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: GITHUBCLIENTEID
        - name: GITHUBCLIENTSECRET
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: GITHUBCLIENTSECRET
        - name: GITHUBCALLBACKURL
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: GITHUBCALLBACKURL
        - name: EMAIL_USER
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: EMAIL_USER
        - name: EMAIL_PASS
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: EMAIL_PASS
        - name: TWILIO_SID
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: TWILIO_SID
        - name: TWILIO_TOKEN
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: TWILIO_TOKEN
        - name: TWILIO_SMS_NUMBER
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: TWILIO_SMS_NUMBER
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi" # Minimum amount of memory guaranteed to the container
            cpu: "250m" # Minimum amount of CPU guaranteed to the container (250 millicpus, or 0.25 of a CPU)
          limits:
            memory: "256Mi" # Maximum amount of memory the container can use
            cpu: "500m" # Maximum amount of CPU the container can use (500 millicpus, or 0.5 of a CPU)
