apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kubedeploy-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kubedeploy
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80